Functions and Graphics
========================================================

```{r}
countOdds <- function(x) sum(x%%2) 


countOdds(1:9)

countOdds(c(1,3,5)) 

countOdds(c(3,5,7,6,2,0))  
```


```{r}
countEvens <- function(x) sum((1+x)%%2)

countEvens(1:9)

countEvens(c(2,4,6))

countEvens(c(1,4,6,9,8))
```

```{r}
hypotenuseLength <- function(x,y) sqrt((x^2)+(y^2))

hypotenuseLength(3,4)
```

```{r}
lawOfCosine <- function(x,y,z) sqrt((x^2)+(y^2)-(2*x*y*cos(z)))

lawOfCosine(13,84,pi/2)

lawOfCosine(13,84,0)

lawOfCosine(5,5,pi/3)

```

```{r}
thetaFromLengths <- function(x,y,z) acos(((x^2)+(y^2)-(z^2))/(2*x*y))

thetaFromLengths(3,4,5)

```

```{r}
thetaFromLengthsTest <- function(x,y,z) {
  sideC <- lawOfCosine(x,y,z)
  angle <- thetaFromLengths(x,y,sideC)
  diff <- (z - angle)
  return(diff)
  }

thetaFromLengthsTest(3,4, pi/2)
```

Graphics
---------------------------
```{r}
canvas <- function(x,y){
  plot(x,y, xaxt ="n", yaxt ="n", xlab = "", ylab = "", asp = 1, type="n", axes = FALSE)
  }
canvas(2,3)
```

```{r}
drawCircle <- function(x,y,r){
  grid.circle(x, y, r, default.units="npc", name=NULL, gp=gpar(), draw=TRUE, vp=NULL)
  }
```


