```{r}
x <- seq(0,1, length=101)
plot(1:2, ylim= c(0,5), xlim = c(0,1), xlab ="x", ylab = "Prob Density", type = "n")
lines(x, dbeta(x,1,2), lwd=1)
lines(x, dbeta(x,1,4), lwd=2)
lines(x, dbeta(x,4,2), lwd=3)
```

```{r}
drawBeta <- function(a,b, ...){
  x <- seq(0,1, length=101)
plot(1:2, ylim= c(0,5), xlim = c(0,1), xlab ="x", ylab = "Prob Density", type = "n")
lines(x, dbeta(x,a,b), lwd=1, ...)
  }
return(drawBeta)
````

```{r}
manipulate({drawBeta(a,b)},
 a =slider(0,10, initial=1, label="a", step=.2),
 b = slider(0,10, initial=2, label="b", step=.2)
 )

```

```{r eval =FALSE}
manipulate(drawBeta(a,b, col=color),
 a =slider(0,10, initial=1, label="a", step=.2),
 b = slider(0,10, initial=2, label="b", step=.2),
 color = picker(list ("red", "blue", "green"))
 )
````

```{r}
betaApp <- function(){
  manipulate(drawBeta(a,b, col=color),
 a =slider(0,10, initial=1, label="a", step=.2),
 b = slider(0,10, initial=2, label="b", step=.2),
 color = picker(list ("red", "blue", "green"))
 )
  }
```
  
